import GetReward from "./getReward";
import LoginCustomer from "./loginCustomer";
import RegisterBusiness from "./RegisterBusiness";
import RegisterCustomer from "./RegisterCustomer";
import LogInBusiness from "./LoginBusiness";
import Home from "./Home";
import BusinessHome from "./BusinessHome";
import CustomerHome from "./CustomerHome";
import TransactionHistory from "./TransactionHistory";
import ProtectedCustomer from "./ProtectedCustomer";
import ProtectedBusiness from "./ProtectedBusiness";
import TermsandCondition from "./TermsandCondition";
import AboutUs from "./AboutUs";
export {AboutUs,TermsandCondition,ProtectedBusiness,ProtectedCustomer,GetReward,TransactionHistory,LoginCustomer,RegisterBusiness,RegisterCustomer,LogInBusiness,Home,BusinessHome,CustomerHome};